apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  namespace: gcp-devops-dev # Add this line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops-gke
  template:
    metadata:
      labels:
        app: gcp-devops-gke
    spec:
      containers:
      - name: gcpdevops-dev
        image: gcr.io/gcp-eks-412117/gcpdevops-dev:latest
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-dev # Add this line
spec:
  selector:
    app: gcp-devops-gke
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
