apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
<<<<<<< HEAD
<<<<<<< HEAD
        image: gcr.io/kodekloud-gcp-training/gcpdevops-dev:latest
=======
        image: gcr.io/cloud-builders/gke-deploy:latest
>>>>>>> 995891d (revision ns)
=======
        image: https://gcr.io/gcp-eks-412117/gcpdevops:latest
>>>>>>> 0afe4b1 (revision ns)
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke-service"
<<<<<<< HEAD
  namespace: "gcp-devops-dev"
=======
  namespace: "gcp-devops-project"
>>>>>>> 995891d (revision ns)
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcp"
  type: "LoadBalancer"
